# Canal de entrada (consumer)
mp.messaging.incoming.order-status.connector=smallrye-kafka
mp.messaging.incoming.order-status.topic=inventory
mp.messaging.incoming.order-status.auto.offset.reset=earliest
mp.messaging.incoming.order-status.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Canal de saída (producer)
mp.messaging.outgoing.inventory-out.connector=smallrye-kafka
mp.messaging.outgoing.inventory-out.topic=inventory
mp.messaging.outgoing.inventory-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
